-- Run this file once in the Supabase SQL editor.
-- Keep Row Level Security enabled. Never expose a service-role key in the website.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room text not null default 'tech-lounge' check (char_length(room) between 1 and 50),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null check (char_length(user_name) between 1 and 40),
  message text not null check (char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);

create table if not exists public.page_comments (
  id bigint generated by default as identity primary key,
  page_slug text not null check (char_length(page_slug) between 1 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null check (char_length(user_name) between 1 and 40),
  comment text not null check (char_length(comment) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_url text not null check (char_length(item_url) between 1 and 500),
  item_title text not null check (char_length(item_title) between 1 and 200),
  created_at timestamptz not null default now(),
  unique (user_id, item_url)
);

create table if not exists public.site_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  report_type text not null check (char_length(report_type) between 1 and 50),
  page_url text not null check (char_length(page_url) between 1 and 500),
  message text not null check (char_length(message) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;
alter table public.page_comments enable row level security;
alter table public.user_favorites enable row level security;
alter table public.site_reports enable row level security;

-- Public reading is intentional for the public chat and public comments.
drop policy if exists "Public can read chat" on public.chat_messages;
create policy "Public can read chat" on public.chat_messages for select using (true);

drop policy if exists "Authenticated users can post chat" on public.chat_messages;
create policy "Authenticated users can post chat" on public.chat_messages
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can delete their chat messages" on public.chat_messages;
create policy "Users can delete their chat messages" on public.chat_messages
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Public can read comments" on public.page_comments;
create policy "Public can read comments" on public.page_comments for select using (true);

drop policy if exists "Authenticated users can post comments" on public.page_comments;
create policy "Authenticated users can post comments" on public.page_comments
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can delete their comments" on public.page_comments;
create policy "Users can delete their comments" on public.page_comments
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can read their favorites" on public.user_favorites;
create policy "Users can read their favorites" on public.user_favorites
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can add their favorites" on public.user_favorites;
create policy "Users can add their favorites" on public.user_favorites
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update their favorites" on public.user_favorites;
create policy "Users can update their favorites" on public.user_favorites
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete their favorites" on public.user_favorites;
create policy "Users can delete their favorites" on public.user_favorites
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Visitors can submit reports" on public.site_reports;
create policy "Visitors can submit reports" on public.site_reports
for insert to anon, authenticated with check (user_id is null or auth.uid() = user_id);

create index if not exists chat_messages_room_created_at_idx on public.chat_messages(room, created_at desc);
create index if not exists page_comments_slug_created_at_idx on public.page_comments(page_slug, created_at desc);
create index if not exists user_favorites_user_created_at_idx on public.user_favorites(user_id, created_at desc);
