"use strict";
(function(){
const topics=Array.isArray(window.WEBSEC_TOPICS)?window.WEBSEC_TOPICS:[];
const labels={all:"الكل",Injection:"Injection",Client:"Client-side",Server:"Server-side",Access:"Access & Identity",Config:"Configuration",API:"API Security",Cloud:"Cloud & Containers"};
const $=id=>document.getElementById(id),grid=$("atlas-grid"),filters=$("atlas-filters"),search=$("atlas-search"),risk=$("atlas-risk"),reviewedOnly=$("atlas-reviewed");let active="all",current=null;
let saved=[];try{saved=JSON.parse(localStorage.getItem("khalid-websec-reviewed-v2")||"[]");}catch{saved=[];}const reviewed=new Set(Array.isArray(saved)?saved:[]);
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
function riskClass(value){return value==="حرج"?"critical":value==="عالي"?"high":"medium";}
function save(){try{localStorage.setItem("khalid-websec-reviewed-v2",JSON.stringify([...reviewed]));}catch{}updateProgress();}
function updateProgress(){const count=reviewed.size;$("atlas-progress-label").textContent=count+" من "+topics.length;$("atlas-progress-bar").style.width=((count/topics.length)*100)+"%";if(current){const button=$("detail-reviewed");const done=reviewed.has(current.id);button.classList.toggle("active",done);button.textContent=done?"تمت المراجعة ✓":"تحديد كمراجع";button.setAttribute("aria-pressed",String(done));}}
function renderFilters(){filters.replaceChildren();Object.keys(labels).forEach(key=>{const count=key==="all"?topics.length:topics.filter(t=>t.category===key).length;const button=el("button","atlas-filter"+(key===active?" active":""));button.type="button";button.append(el("span","",labels[key]),el("span","",String(count)));button.addEventListener("click",()=>{active=key;renderFilters();render();});filters.append(button);});}
function searchText(t){return [t.title,t.description,t.impact,t.rootCause,labels[t.category],...t.signs,...t.checks,...t.defenses,...t.logging].join(" ").toLowerCase();}
function visibleTopics(){const q=search.value.trim().toLowerCase();return topics.filter(t=>(active==="all"||t.category===active)&&(risk.value==="all"||t.risk===risk.value)&&(!reviewedOnly.checked||reviewed.has(t.id))&&(!q||searchText(t).includes(q)));}
function render(){const visible=visibleTopics();grid.replaceChildren();visible.forEach(topic=>{const card=el("article","atlas-card"+(reviewed.has(topic.id)?" reviewed":""));const top=el("div","atlas-card-top");top.append(el("span","atlas-category",labels[topic.category]),el("span","risk-badge "+riskClass(topic.risk),topic.risk));const meta=el("div","atlas-card-meta");meta.append(el("span","",topic.signs.length+" دلائل"),el("span","",topic.checks.length+" خطوات تحقق"),el("span","",topic.defenses.length+" معالجات"));const button=el("button","","فتح الشرح الموسع");button.type="button";button.addEventListener("click",()=>openTopic(topic));card.append(top,el("h3","",topic.title),el("p","",topic.description),meta,button);grid.append(card);});$("atlas-count").textContent=visible.length+" من "+topics.length+" موضوعًا";$("atlas-empty").hidden=visible.length!==0;}
function fillList(id,items,ordered=false){const list=$(id);list.replaceChildren();items.forEach(item=>list.append(el("li","",item)));}
function openTopic(topic){current=topic;document.querySelector(".atlas-directory").hidden=true;const section=$("atlas-detail-section");section.hidden=false;$("detail-category").textContent=labels[topic.category];$("detail-title").textContent=topic.title;const badge=$("detail-risk");badge.className="risk-badge "+riskClass(topic.risk);badge.textContent="الخطورة: "+topic.risk;$("detail-description").textContent=topic.description;$("detail-impact").textContent=topic.impact;$("detail-root").textContent=topic.rootCause;$("detail-scenario").textContent=topic.scenario;fillList("detail-signs",topic.signs);fillList("detail-checks",topic.checks);fillList("detail-defenses",topic.defenses);fillList("detail-logging",topic.logging);fillList("detail-checklist",topic.checklist,true);const related=$("detail-related");related.replaceChildren();topic.related.map(id=>topics.find(item=>item.id===id)).filter(Boolean).forEach(item=>{const button=el("button","",item.title);button.type="button";button.addEventListener("click",()=>openTopic(item));related.append(button);});updateProgress();try{history.replaceState(null,"",location.pathname+"#"+topic.id);}catch{}section.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}
$("detail-reviewed").addEventListener("click",()=>{if(!current)return;if(reviewed.has(current.id))reviewed.delete(current.id);else reviewed.add(current.id);save();render();});
$("atlas-back").addEventListener("click",()=>{$("atlas-detail-section").hidden=true;document.querySelector(".atlas-directory").hidden=false;current=null;try{history.replaceState(null,"",location.pathname);}catch{}render();document.querySelector(".atlas-directory").scrollIntoView({behavior:"smooth"});});
$("atlas-reset").addEventListener("click",()=>{reviewed.clear();save();render();});search.addEventListener("input",render);risk.addEventListener("change",render);reviewedOnly.addEventListener("change",render);renderFilters();updateProgress();render();const initial=topics.find(item=>item.id===location.hash.slice(1));if(initial)openTopic(initial);
})();
