"use strict";
(function(){
const labs=Array.isArray(window.SECURITY_LABS)?window.SECURITY_LABS:[];

const $=id=>document.getElementById(id),grid=$("lab-grid"),workspace=$("workspace"),search=$("lab-search"),level=$("lab-level"),domain=$("lab-domain");
let saved=[];try{saved=JSON.parse(localStorage.getItem("khalid-security-labs-v2")||"[]");}catch{saved=[];}const completed=new Set(Array.isArray(saved)?saved:[]);
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
function save(){try{localStorage.setItem("khalid-security-labs-v2",JSON.stringify([...completed]));}catch{}updateProgress();}
function updateProgress(){const count=completed.size;$("lab-progress-label").textContent=count+" من "+labs.length;$("lab-progress-bar").style.width=((count/labs.length)*100)+"%";}
function initDomains(){[...new Set(labs.map(l=>l.domain))].sort((a,b)=>a.localeCompare(b,"ar")).forEach(value=>{const o=el("option","",value);o.value=value;domain.append(o);});}
function visibleLabs(){const q=search.value.trim().toLowerCase();return labs.filter(l=>(level.value==="all"||l.level===level.value)&&(domain.value==="all"||l.domain===domain.value)&&(!q||(l.title+" "+l.summary+" "+l.domain+" "+l.tools.join(" ")).toLowerCase().includes(q)));}
function renderCards(){const visible=visibleLabs();grid.replaceChildren();$("lab-result-count").textContent="عرض "+visible.length+" من "+labs.length+" مختبرًا";visible.forEach(lab=>{const card=el("article","lab-card"+(completed.has(lab.id)?" completed":""));const top=el("div","lab-card-top");top.append(el("span","lab-code",lab.code),el("span","lab-level",lab.level));const meta=el("div","lab-card-meta");meta.append(el("span","",lab.evidence.length+" أدلة"),el("span","",lab.tasks.length+" خطوات"),el("span","",lab.mappings.length+" تقنيات"));const button=el("button","",completed.has(lab.id)?"إعادة المختبر":"ابدأ المختبر");button.type="button";button.addEventListener("click",()=>openLab(lab));card.append(top,el("span","lab-card-domain",lab.domain),el("h3","",lab.title),el("p","",lab.summary),meta,button);grid.append(card);});}
function fillList(id,items){const list=$(id);list.replaceChildren();items.forEach(item=>list.append(el("li","",item)));}
function fillChips(id,items){const box=$(id);box.replaceChildren();items.forEach(item=>box.append(el("span","",item)));}
function openLab(lab){$("labs").hidden=true;workspace.hidden=false;$("lab-code").textContent=lab.code+" · "+lab.level;$("lab-domain-label").textContent=lab.domain;$("lab-title").textContent=lab.title;$("lab-summary").textContent=lab.summary;$("lab-objective").textContent=lab.objective;fillList("hypothesis-list",lab.hypotheses);fillChips("tool-list",lab.tools);fillChips("mapping-list",lab.mappings);const evidence=$("evidence-list");evidence.replaceChildren();lab.evidence.forEach(([name,value,meaning])=>{const item=el("article","evidence-item");item.append(el("strong","",name),el("code","",value),el("small","",meaning));evidence.append(item);});fillList("task-list",lab.tasks);$("lab-question").textContent=lab.question;const options=$("decision-options"),feedback=$("decision-feedback"),debrief=$("lab-debrief");options.replaceChildren();feedback.hidden=true;feedback.textContent="";debrief.hidden=true;lab.choices.forEach((choice,index)=>{const button=el("button","",String.fromCharCode(65+index)+". "+choice);button.type="button";button.addEventListener("click",()=>{options.querySelectorAll("button").forEach((b,i)=>{b.disabled=true;if(i===lab.answer)b.classList.add("correct");else if(i===index)b.classList.add("wrong");});feedback.hidden=false;feedback.textContent=(index===lab.answer?"إجابة صحيحة. ":"راجع القرار. ")+lab.explanation;fillList("takeaway-list",lab.takeaways);debrief.hidden=false;if(index===lab.answer){completed.add(lab.id);save();}});options.append(button);});try{history.replaceState(null,"",location.pathname+"#"+lab.id);}catch{}workspace.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}
$("lab-back").addEventListener("click",()=>{workspace.hidden=true;$("labs").hidden=false;try{history.replaceState(null,"",location.pathname);}catch{}renderCards();$("labs").scrollIntoView({behavior:"smooth"});});
$("lab-reset").addEventListener("click",()=>{completed.clear();save();renderCards();});[search,level,domain].forEach(node=>node.addEventListener(node===search?"input":"change",renderCards));initDomains();updateProgress();renderCards();const initial=labs.find(item=>item.id===location.hash.slice(1));if(initial)openLab(initial);
})();
